name: Pull repository

on: [push]

jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    env: 
      WORKING_DIRECTORY: /home/webmaster/git/Numeroteca
    steps:
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
        host: github.com
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Pull repository
      run: git pull 
      working-directory: ${{ WORKING_DIRECTORY }}
